language: python

python:
  - "3.6"

services:
  - postgresql

env:
  - DATABASE_URL = 'postgres://postgres@localhost/test_db'

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=authors/ manage.py test
  - coverage report -m
  - coveralls
after_success:
  - coveralls