language: python
 
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

script:
  - coverage run manage.py test

after_success:
  - coveralls