language: python

python:
  - "3.6"

services:
  - postgresql

env:
  - DATABASE_URL = 'postgres://postgres@localhost/test_db'

install:
  - pip install -r requirements.txt

before_install:
  - psql -c 'create database test_db;' -U postgres

script:
  - coverage run manage.py test authors

after_success:
  - coveralls