language: python  
python:
  - "3.6"
services:
  - postgresql
before_install:
  - psql -c “create database postgres;” -U postgres
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
script: python manage.py test