# Generated by Django 2.1.1 on 2018-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fun_fact',
            field=models.TextField(blank=True),
        ),
    ]
